Add prettier standard guidelines
schmiedeone/vacabot pull request #16
Opened 2020-10-11 23:35 UTC by Izzur

This PR related with #13  
I have add standard .prettierrc to set default tab size, also set to auto format on save in vscode

2020-10-12 18:06 UTC, mukarramali requested changes

2020-10-12 18:06 UTC, mukarramali commented on .prettierrc
> +  "endOfLine": "auto"
use `lf` for endOfLine, following Airbnb style guides

2020-10-12 18:06 UTC, mukarramali commented on .prettierrc
> +  "singleQuote": false,
singleQuote as true, please refer to https://github.com/airbnb/javascript#strings--quotes

2020-10-12 18:24 UTC, mukarramali commented
Please link issues you are working on

2020-10-12 22:47 UTC, Izzur commented
I update the .prettierrc as requested 
This PR related with issue #13

2020-10-13 06:56 UTC, mukarramali approved these changes

2020-10-13 06:56 UTC, merged